#!/bin/bash

print_help()
{
  echo "lsub - submit a bash script to the lbatch queue"
  echo "Usage: lsub [batch script] [options] "
  echo " "
  echo "options:"
  echo "  -h,     show help"
  echo "  -n,     maximum number of job slots [default "$1"]"
  echo "  -t,     number of jobs to be scheduled [default 0]"
  echo "  -j,     batch file for submitting jobs"
}

# Variable init
NJOBS=0

if [[ "$(uname)" = "Darwin" ]] ; then
  NSLOTS=$(sysctl -n hw.logicalcpu_max)
else
  NSLOTS=$(lscpu -p | awk '{if ($1!="#") print;}' | wc -l )
fi

if [[ $# -eq 0 ]] ; then
    print_help $NSLOTS
    exit 0
fi

NARGS=3
while test $NARGS -gt 0; do
        case "$1" in
                -h|--help)
                        print_help $NSLOTS
                        exit 0
                        ;;
                -n)
                        shift
                        NSLOTS=$1
                        shift
                        ;;
                -t)
                        shift
                        NJOBS=$1
                        shift
                        ;;
                -j)
                        shift
                        SCRIPTFILE=$1
                        shift
                        ;;
                *)
                        break
                        ;;
        esac
done

echo $NJOBS " jobs requested for job script " $SCRIPTFILE

if [ $NJOBS == 0 ]; then
  echo "lbatch error: zero jobs requested";
  exit 1;
fi

if [ ! -f $SCRIPTFILE ]; then
    echo "lbatch error: batch script $SCRIPTFILE cannot be found";
    exit 1;
fi

nohup lbatch-sh $SCRIPTFILE $NJOBS $NSLOTS &> /dev/null &
echo "lbatch: job " $SCRIPTFILE " submitted" 
